# Generated by Django 5.0.1 on 2024-05-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cookiedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
